FROM python:3.12-slim

WORKDIR /app

COPY Workshop-3/core-service/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY Workshop-3/core-service /app

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
